//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        public string IdChiTietDonHang { get; set; } = Guid.NewGuid().ToString();
        public Nullable<System.DateTime> NgayDatHang { get; set; }
        public string TenNguoiNhan { get; set; }
        public string SDT { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public string IdDonHang { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public string TinNhan { get; set; }
        public string TinhTrangThanhToan { get; set; }
        public string CodeOrder { get; set; }
        public string PhuongThucThanhToan { get; set; }
        public string Status { get; set; }
    
        public virtual DonHang DonHang { get; set; }
    }
}
