//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
        }
    
        public string IdDonHang { get; set; } = Guid.NewGuid().ToString();
        public string IdSanPham { get; set; }
        public Nullable<decimal> GiaSanPham { get; set; }
        public int SoLuong { get; set; }
        public string LoaiSize { get; set; }
        public string TinNhan { get; set; }
        public string IdUser { get; set; }
        public string CodeOrder { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        public virtual SanPham SanPham { get; set; }
        public virtual Users Users { get; set; }
    }
}
