//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public string IdGioHang { get; set; } = Guid.NewGuid().ToString();
        public string IdUser { get; set; }
        public string IdSanPham { get; set; }
        public string TinNhan { get; set; }
        public Nullable<decimal> GiaSanPham { get; set; }
        public int SoLuong { get; set; }
        public string TLoaiSize { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        public virtual Users Users { get; set; }
    }
}
